---
# Secure this file via `ansible-vault encrypt vars/secrets.yml`
# This secret is not hashed, it is plaintext but secured via ansible-vault AES256
pihole_secret: # plaintext value

# This secret must be hashed beforehand as ansible.builtin.user requires
# the 'password:' vaule be hashed in some way
# https://docs.ansible.com/projects/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
# example hashing command:
#    python3 -c "from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.using(rounds=5000).hash(getpass.getpass()))"
pihole_user_pass: # hashed value
