---
# Secure this file via `ansible-vault encrypt files/secrets.yml`
# This secret is not hashed, it is plaintext but secured via ansible-vault AES256
pihole_secret: # plaintext value

# This secret must be hashed beforehand as ansible.builtin.user requires
# the 'password:' key be hashed in some way
# https://docs.ansible.com/projects/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
pihole_user_pass: # hashed value
